config/routes.rb
    scope 'post-types' do
      root                                 to: 'post_types#index', as: :post_types
      get    'new',                        to: 'post_types#new', as: :new_post_type
      post   'new',                        to: 'post_types#create', as: :create_post_type
      get    ':id/edit',                   to: 'post_types#edit', as: :edit_post_type
      patch  ':id/edit',                   to: 'post_types#update', as: :update_post_type
    end
  end

  get    'close_reasons',                  to: 'close_reasons#index', as: :close_reasons
  get    'close_reasons/edit/:id',         to: 'close_reasons#edit', as: :close_reason
  patch  'close_reasons/edit/:id',         to: 'close_reasons#update', as: :update_close_reason
  get    'close_reasons/new',              to: 'close_reasons#new', as: :new_close_reason
  post   'close_reasons/new',              to: 'close_reasons#create', as: :create_close_reason

  scope  'admin/tag-sets' do
    root                                   to: 'tag_sets#index', as: :tag_sets
    get    'global',                       to: 'tag_sets#global', as: :global_tag_sets
    get    ':id',                          to: 'tag_sets#show', as: :tag_set
    post   ':id/edit',                     to: 'tag_sets#update', as: :update_tag_set
  end

  scope 'admin/licenses' do
    root                                   to: 'licenses#index', as: :licenses
    get    'new',                          to: 'licenses#new', as: :new_license
    post   'new',                          to: 'licenses#create', as: :create_license
    get    ':id/edit',                     to: 'licenses#edit', as: :edit_license
    patch  ':id/edit',                     to: 'licenses#update', as: :update_license
    post   ':id/toggle',                   to: 'licenses#toggle', as: :toggle_license
  end

  scope 'mod' do
    root                                   to: 'moderator#index', as: :moderator
    get    'deleted',                      to: 'moderator#recently_deleted_posts', as: :recently_deleted_posts
    get    'comments',                     to: 'moderator#recent_comments', as: :recent_comments
    get    'flags',                        to: 'flags#queue', as: :flag_queue
    get    'flags/handled',                to: 'flags#handled', as: :handled_flags
    get    'flags/escalated',              to: 'flags#escalated_queue', as: :escalated_flags
    delete 'users/destroy/:id',            to: 'users#destroy', as: :destroy_user
    get    'users/votes/:id',              to: 'moderator#user_vote_summary', as: :mod_vote_summary
    post   'flags/:id/resolve',            to: 'flags#resolve', as: :resolve_flag
    post   'flags/:id/escalate',           to: 'flags#escalate', as: :escalate_flag

    scope 'featured' do
      root                                 to: 'pinned_links#index', as: :pinned_links
      get   'new',                         to: 'pinned_links#new', as: :new_pinned_link
      post  'new',                         to: 'pinned_links#create', as: :create_pinned_link
      get   ':id/edit',                    to: 'pinned_links#edit', as: :edit_pinned_link
      patch ':id/edit',                    to: 'pinned_links#update', as: :update_pinned_link
    end
  end

  get    'questions/lottery',              to: 'questions#lottery', as: :questions_lottery

  scope 'posts/reactions' do
    root                                  to: 'reactions#index', as: :reactions
    get   ':id/edit',                     to: 'reactions#edit', as: :edit_reaction
    patch ':id/edit',                     to: 'reactions#update', as: :update_reaction
    get   'new',                          to: 'reactions#new', as: :new_reaction
    post  'new',                          to: 'reactions#create', as: :create_reaction

    post  'add',                          to: 'reactions#add', as: :add_reaction
    post  'retract',                      to: 'reactions#retract', as: :retract_reaction
  end

  scope 'posts' do
    scope 'suggested-edit' do
      get    ':id',           to: 'suggested_edit#show', as: :suggested_edit
      post   ':id/approve',   to: 'suggested_edit#approve', as: :suggested_edit_approve
      post   ':id/reject',    to: 'suggested_edit#reject', as: :suggested_edit_reject
    end

    get    'new/:post_type',               to: 'posts#new', as: :new_post
    get    'new/:post_type/respond/:parent', to: 'posts#new', as: :new_response
    get    'new/:post_type/:category',     to: 'posts#new', as: :new_category_post
    post   'new/:post_type',               to: 'posts#create', as: :create_post
    post   'new/:post_type/respond/:parent', to: 'posts#create', as: :create_response
    post   'new/:post_type/:category',     to: 'posts#create', as: :create_category_post
    get    'search',                       to: 'search#search', as: :search
    get    'promoted',                     to: 'moderator#promotions', as: :promoted_posts
    get    'types',                        to: 'post_types#list', as: :post_types_list
    post   'upload',                       to: 'posts#upload', as: :upload
    post   'save-draft',                   to: 'posts#save_draft', as: :save_draft
    post   'delete-draft',                 to: 'posts#delete_draft', as: :delete_draft

    get    ':id',                          to: 'posts#show', as: :post
    get    ':id/history',                  to: 'post_history#post', as: :post_history
    get    ':id/edit',                     to: 'posts#edit', as: :edit_post
    patch  ':id/edit',                     to: 'posts#update', as: :update_post
    post   ':id/close',                    to: 'posts#close', as: :close_post
    post   ':id/reopen',                   to: 'posts#reopen', as: :reopen_post
    post   ':id/delete',                   to: 'posts#delete', as: :delete_post
    post   ':id/restore',                  to: 'posts#restore', as: :restore_post
    post   ':id/category',                 to: 'posts#change_category', as: :change_category
    post   ':id/toggle_comments',          to: 'posts#toggle_comments', as: :post_comments_allowance_toggle
    post   ':id/lock',                     to: 'posts#lock', as: :post_lock
    post   ':id/unlock',                   to: 'posts#unlock', as: :post_unlock
    post   ':id/feature',                  to: 'posts#feature', as: :post_feature
    post   ':id/promote',                  to: 'moderator#nominate_promotion', as: :promote_post
    delete ':id/promote',                  to: 'moderator#remove_promotion', as: :remove_post_promotion

    get    ':id/:answer',                  to: 'posts#show', as: :answer_post
  end

  get    'policy/:slug',                   to: 'posts#document', as: :policy
  get    'help/:slug',                     to: 'posts#document', as: :help

  get    'tags',                           to: 'tags#index', as: :tags

  scope 'users/two-factor' do
    root                                   to: 'two_factor#tf_status', as: :two_factor_status
    post 'enable',                         to: 'two_factor#enable_2fa', as: :two_factor_enable
    get  'enable/code',                    to: 'two_factor#enable_code', as: :two_factor_enable_code
    post 'enable/code',                    to: 'two_factor#confirm_enable_code', as: :two_factor_confirm_enable
    get  'disable/code',                   to: 'two_factor#disable_code', as: :two_factor_disable_code
    post 'disable/code',                   to: 'two_factor#confirm_disable_code', as: :two_factor_confirm_disable
    post 'disable/link-email',             to: 'two_factor#send_disable_email', as: :two_factor_send_disable_email
    get  'disable/link/:token',            to: 'two_factor#disable_link', as: :two_factor_disable_link
    post 'disable/link',                   to: 'two_factor#confirm_disable_link', as: :two_factor_confirm_disable_link
  end

  scope  'users' do
    root                                to: 'users#index', as: :users
    get    '/stack-redirect',           to: 'users#stack_redirect', as: :stack_redirect
    post   '/claim-content',            to: 'users#transfer_se_content', as: :claim_stack_content
    get    '/mobile-login',             to: 'users#qr_login_code', as: :qr_login_code
    get    '/mobile-login/:token',      to: 'users#do_qr_login', as: :qr_login
    get    '/me',                       to: 'users#me', as: :users_me
    get    '/me/preferences',           to: 'users#preferences', as: :user_preferences
    post   '/me/preferences',           to: 'users#set_preference', as: :set_user_preference
    get    '/me/notifications',         to: 'notifications#index', as: :notifications
    get    '/edit/profile',             to: 'users#edit_profile', as: :edit_user_profile
    patch  '/edit/profile',             to: 'users#update_profile', as: :update_user_profile
    get    '/me/vote-summary',          to: 'users#my_vote_summary', as: :my_vote_summary
    get    '/avatar/:letter/:color/:size', to: 'users#specific_avatar', as: :specific_auto_avatar
    get    '/:id',                      to: 'users#show', as: :user
    get    '/:id/flags',                to: 'flags#history', as: :flag_history
    get    '/:id/activity',             to: 'users#activity', as: :user_activity
    get    '/:id/mod',                  to: 'users#mod', as: :mod_user
    get    '/:id/posts',                to: 'users#posts', as: :user_posts
    get    '/:id/vote-summary',         to: 'users#vote_summary', as: :vote_summary
    get    '/:id/mod/privileges',       to: 'users#mod_privileges', as: :user_privileges
    post   '/:id/mod/privileges',       to: 'users#mod_privilege_action', as: :user_privilege_action
    post   '/:id/mod/toggle-role',      to: 'users#role_toggle', as: :toggle_user_role
    get    '/:id/mod/annotations',      to: 'users#annotations', as: :user_annotations
    post   '/:id/mod/annotations',      to: 'users#annotate', as: :annotate_user
    get    '/:id/mod/activity-log',     to: 'users#full_log', as: :full_user_log

app/models/reaction_type.rb
class ReactionType < ApplicationRecord
  include CommunityRelated
  belongs_to :post_type, class_name: 'PostType', optional: true

  validates :name, uniqueness: { scope: [:community_id], case_sensitive: false }

  scope :active, -> { where(active: true) }
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_moderator, except: [:add, :retract]
  before_action :set_post, only: [:add, :retract]
  before_action :set_reaction_type, only: [:edit, :update]

  def add
    reaction_type = ReactionType.find(params[:reaction_id])
    comment_text = params[:comment]
    comment = nil

    if !comment_text.blank?
      if @post.comments_disabled && !current_user.is_moderator && !current_user.is_admin
        render json: { status: 'failed', message: 'Comments have been disabled on this post.' }, status: :forbidden
        return
      end

      thread = CommentThread.find_or_create_by(title: reaction_type.name, post: @post)

      comment = Comment.new(post: @post, content: comment_text, user: current_user, comment_thread: thread)
    elsif reaction_type.requires_comment
      render json: { status: 'failed', message: 'This reaction type requires a comment with an explanation.' },
             status: :forbidden
      return
    end

    old_reaction = Reaction.where(user: current_user, post: @post, reaction_type: reaction_type)
    if old_reaction.any?
      render json: { status: 'failed', message: 'You already added this reaction to this post.' },
             status: :forbidden
      return
    end

    reaction = Reaction.new(user: current_user, post: @post, reaction_type: reaction_type, comment: comment)

    ActiveRecord::Base.transaction do
      thread&.save!
      comment&.save!
      reaction.save!
    end

    render json: { status: 'success' }
  end

  def retract
    reaction_type = ReactionType.find(params[:reaction_id])

    reaction = Reaction.where(user: current_user, post: @post, reaction_type: reaction_type)
    unless reaction.any?
      render json: { status: 'failed', message: 'You do not have any reactions of this type on this post.' },
             status: :forbidden
      return
    end

    reaction.first.destroy
    render json: { status: 'success' }
  end

  def index; end

  def edit; end

  def update
    @reaction_type.update reaction_type_params
    PostType.mapping.each_key { |pt| Rails.cache.delete("post_type/#{pt}/reactions") }
    redirect_to reactions_path
  end

  def new
    @reaction_type = ReactionType.new
  end

  def create
    ReactionType.create reaction_type_params
    PostType.mapping.each_key { |pt| Rails.cache.delete("post_type/#{pt}/reactions") }
    redirect_to reactions_path
  end

  protected

  def set_post
    @post = Post.find(params[:post_id])
    unless @post.can_access?(current_user)
      not_found
    end
  end

  def set_reaction_type
    @reaction_type = ReactionType.find(params[:id])
  end

  def reaction_type_params
    params.require(:reaction_type).permit(:name, :description, :on_post_label, :color, :icon,
                                          :requires_comment, :active, :position, :post_type_id)
  end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_dialog.html.erb
<%
    user_reactions_types = post.reactions.where(user: current_user) \
                               .map { |r| r.reaction_type }
%>
<div class="droppanel is-large droppanel-for-reactions" id="post-<%= post.id %>-reactions-panel">
  <div class="droppanel--header">
    Mark this <%= post.post_type.name.downcase %> as ...
  </div>
  <% post.post_type.reactions.each do |rt| %>
    <div class="grid">
      <div class="grid--cell">
        <input class="form-radio-element reaction-type" type="radio" name="reaction-type"
                value="<%= rt.id %>"
                id="reaction-type-input-<%= post.id %>-<%= rt.id %>"
                <%= rt.requires_comment ? 'data-reaction-require-comment' : '' %>
                <%= 'disabled' if user_reactions_types.include? rt %>>
      </div>
      <div class="grid--cell is-flexible">
        <label class="form-element <%= 'disabled' if user_reactions_types.include? rt %>"
               for="reaction-type-input-<%= post.id %>-<%= rt.id %>" >
          <span class="badge is-tag <%= rt.color %>">
            <i class="<%= rt.icon %> fa-fw"></i>
            <%= rt.name %>
          </span>
          <% if user_reactions_types.include? rt %>
          (used already;
          <a href="#" class="reaction-retract" data-reaction="<%= rt.id %>" data-post="<%= post.id %>">retract?</a>)
          <% elsif rt.requires_comment %>
          (requires comment)
          <% end %>
          <div class="form-caption">
            <%= raw render_markdown(rt.description) %>
          </div>
        </label>
      </div>
    </div>
  <% end %>
  <label for="reaction-type-comment-<%= post.id %>">Explain in comment?</label>
  <textarea class="form-element reaction-comment-field is-small"
            id="reaction-type-comment-<%= post.id %>"></textarea>
  <button type="button" class="button is-filled reaction-submit" data-post-id="<%= post.id %>">
    Add reaction
  </button>
</div>

app/views/reactions/_form.html.erb
<%= form_for @reaction_type, url: submit_url, method: method do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name", class: "form-element" %>
    <%= f.text_field :name, class: "form-element" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description", class: "form-element" %>
    <%= f.text_area :description, class: "form-element is-small" %>
  </div>

  <div class="form-group">
    <%= f.label :on_post_label, "Label on Post", class: "form-element" %>
    <div class="form-caption">
        This label will be shown on posts marked with this reaction; directly followed by a list of people who used it. Should end in a preposition such as "for" or "by"
    </div>
    <%= f.text_field :on_post_label, class: "form-element" %>
  </div>

  <div class="form-group">
    <%= f.label :color, "Color", class: "form-element" %>
    <div class="form-caption">
    </div>
    <%= f.select(:color, [
          ['blue (light)', ''], ['blue (dark)', 'is-filled'],
          ['red (light)', 'is-red'], ['red (dark)', 'is-red is-filled'],
          ['yellow (light)', 'is-yellow'], ['yellow (dark)', 'is-yellow is-filled'],
          ['green (light)', 'is-green'], ['green (dark)', 'is-green is-filled'],
          ['teal (light)', 'is-teal'], ['teal (dark)', 'is-teal is-filled'],
          ['gray (light)', 'is-muted'], ['gray (dark)', 'is-muted is-filled']
        ], {}, { class: "form-element" }) %>
  </div>

  <div class="form-group">
    <%= f.label :icon, "Icon", class: "form-element" %>
    <div class="form-caption">
      The code for a <a href="https://fontawesome.com/">FontAwesome</a> (free) icon to be used for this reaction. Has two parts separated by space (<code>faX</code> for the icon set and <code>fa-X</code> for the icon code).
    </div>
    <%= f.text_field :icon, class: "form-element", placeholder: 'fas fa-exclamation-triangle' %>
  </div>

  <div class="form-group">
    <div class="checkbox-setting">
      <div class="checkbox-setting--desc">
        <%= f.label :requires_comment, 'Require comment?', class: 'form-element' %>
        <span class="form-caption">
          Check this box if the reaction requires users to add a comment explaining their reaction. Should be used sparingly, as it can facilitate circumvention.
        </span>
      </div>
      <div class="checkbox-setting--value">
        <%= f.check_box :requires_comment, class: 'form-checkbox-element' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="checkbox-setting">
      <div class="checkbox-setting--desc">
        <%= f.label :active, 'Active?', class: 'form-element' %>
        <span class="form-caption">
          Check this box if the reaction is active and can be added to posts by anyone.
        </span>
      </div>
      <div class="checkbox-setting--value">
        <%= f.check_box :active, class: 'form-checkbox-element' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :post_type_id, "Limited to Post Type", class: "form-element" %>
    <div class="form-caption">
      You can limit the availability of this reaction type to one specific post type; if left blank, the reaction will be available for all post types that are not restricting reactions to specific ones.
    </div>
    <%= f.select(:post_type_id, ([['', nil]] + PostType.all.map { |pt| [pt.name.underscore.humanize, pt.id] }), {}, { class: "form-element" }) %>
  </div>

  <div class="form-group">
    <%= f.label :position, "Position", class: "form-element" %>
    <div class="form-caption">
      The order in which the reactions are to be shown in the add reaction dialog; lower positions go first
    </div>
    <%= f.number_field :position, class: "form-element" %>
  </div>

  <%= f.submit 'Save', class: 'button is-filled' %>
  <%= link_to 'Cancel', reactions_path, class: 'button' %>
<% end %>

app/views/reactions/_list.html.erb
<% reaction_shown_count = 3 %>
<div class="h-d-flex reactions-list">
    <% post.reaction_list.each do |rt, rr| %>
        <a href="#x" class="badge is-tag is-reaction <%= rt.color %>"
           data-modal="#reaction-info-<%= post.id %>-<%= rt.id %>"
           title="<%= rt.description %>">
            <i class="<%= rt.icon %> fa-fw"></i>
            <%= rt.on_post_label %>
            <% rr.each_with_index do |r, i| %>
                <% next if i >= reaction_shown_count %>
                <span dir="ltr"><%=
                    r.user.rtl_safe_username
                %></span><%=
                    ((i < rr.size - 1 && i + 1 != reaction_shown_count) ? ', ' : '')
                %>
            <% end %>
            <% if rr.size > reaction_shown_count %>
                and <%=
                    rr.size - reaction_shown_count
                %> other<%=
                    (rr.size - reaction_shown_count) == 1 ? '' : 's'
                %>
            <% end %>
        </a>
    <% end %>
</div>

<% post.reaction_list.each do |rt, rr| %>
    <div class="modal is-with-backdrop reaction-info-modal"
         id="reaction-info-<%= post.id %>-<%= rt.id %>">
        <div class="modal--container">
            <div class="modal--header">
                <button class="button is-close-button modal--header-button"
                        data-modal="#reaction-info-<%= post.id %>-<%= rt.id %>">
                    &times;
                </button>
                <%= rt.name %>
            </div>
            <div class="modal--body">
                <p>The following users marked this post as <em><%= rt.name %></em>:</p>
                <table class="table">
                    <tr>
                        <th>User</th>
                        <th class="comment-col">Comment</th>
                        <th>Date</th>
                    </tr>
                    <% rr.each do |r| %>
                    <tr>
                        <td>
                            <%= link_to r.user.rtl_safe_username, user_path(r.user), dir: 'ltr'%>
                        </td>
                        <td class="comment-col">
                            <% if r.comment %>
                                <div class="muted-p">
                                    <p class="h-fw-bold">
                                        Thread:
                                        <%= link_to r.comment.comment_thread.title, comment_link(r.comment) %>
                                    </p>
                                    <% if r.comment.content.size < 150 %>
                                    <%= raw(sanitize(render_markdown(r.comment.content),
                                                     scrubber: CommentScrubber.new)) %>
                                    <% else %>
                                    <%= raw(sanitize(render_markdown(r.comment.content[0..150] + "..."),
                                                     scrubber: CommentScrubber.new)) %>
                                    <% end %>
                                </div>
                            <% else %>
                            <em>(no comment)</em>
                            <% end %>
                        </td>
                        <td class="h-fs-caption">
                            <%= r.created_at.strftime('%b %e, %Y at %H:%M') %>
                        </td>
                    </tr>
                    <% end %>
                </table>
            </div>
        </div>
    </div>
<% end %>

app/views/reactions/edit.html.erb
<h1>Edit reaction</h1>

<div class="notice is-warning has-color-yellow-900 has-font-size-caption flex-row-always jc-sb ai-c">
  <i class="fas fa-exclamation-triangle"></i>
  <div>
    If you edit the details for this reaction, the change will appear on all questions that are already
    marked with this reason.
  </div>
</div>

<% if @reaction_type.errors.any? %>
  <div class="notice is-danger">
    These errors prevented this reaction type being saved:
    <ul>
      <% @reaction_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form', submit_url: update_reaction_path(@reaction_type.id), method: :patch %>

app/views/reactions/index.html.erb
<%= link_to moderator_path, class: 'has-font-size-small' do %>
  &laquo; Return to moderator tools
<% end %>

<h1>Reactions</h1>

<p class="is-lead">Reactions can be used to give feedback to post authors and to give hints to readers regarding the usefulness, safety, ... of an post. Use them sparely and only when necessary</p>

<table>
    <tr>
        <th>reaction</th>
        <th>description</th>
        <th>label on post</th>
        <th>requires comment?</th>
        <th>active?</th>
        <th>actions</th>
    </tr>
    <% ReactionType.all.each do |rt| %>
    <tr>
        <td>
            <span class="badge is-tag is-reaction <%= rt.color %>">
                <i class="<%= rt.icon %> fa-fw"></i>
                <%= rt.name %>
            </span>
        </td>
        <td>
            <%= rt.description %>
        </td>
        <td>
            <%= rt.on_post_label %> <em>user(s)</em>
        </td>
        <td>
            <%= rt.requires_comment ? 'yes' : 'no' %>
        </td>
        <td>
            <%= rt.active ? 'yes' : 'no' %>
        </td>
        <td>
            <div class="h-d-flex">
                <%= link_to "edit", edit_reaction_path(rt.id), class: "button is-outlined" %>
            </div>
        </td>
    </tr>
    <% end %>
</table>

<div class="notice has-margin-top-4">
    <p>
        You can add further reactions.
        Please try to keep the number low, as many reasons quickly become overwhelming.
        Do not add reasons where you're not sure that your community needs or wants them.
        Do not add reasons to circumvent votes.
    </p>
    <p>
        Once a reaction has been created, it can only be deactivated, not deleted.
    </p>
    <%= link_to "add reaction", new_reaction_path, class: "button is-outlined" %>
</div>

app/views/reactions/new.html.erb
<h1>New reaction</h1>

<% if @reaction_type.errors.any? %>
  <div class="notice is-danger">
    These errors prevented this reaction type being saved:
    <ul>
      <% @reaction_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form', submit_url: create_reaction_path, method: :post %>