config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get  'users/2fa/login',                to: 'users/sessions#verify_2fa', as: :login_verify_2fa
    post 'users/2fa/login',                to: 'users/sessions#verify_code', as: :login_verify_code
  end

  root                                     to: 'categories#homepage'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  
  
  scope 'admin' do
    root                                   to: 'admin#index', as: :admin
    get    'errors',                       to: 'admin#error_reports', as: :admin_error_reports

    get    'settings',                     to: 'site_settings#index', as: :site_settings
    get    'settings/global',              to: 'site_settings#global', as: :global_settings
    get    'settings/:name',               to: 'site_settings#show', as: :site_setting
    post   'settings/:name',               to: 'site_settings#update', as: :update_site_setting

    delete 'users/delete/:id',             to: 'users#soft_delete', as: :soft_delete_user

    get    'privileges',                   to: 'admin#privileges', as: :admin_privileges
    get    'privileges/:name',             to: 'admin#show_privilege', as: :admin_privilege
    post   'privileges/:name',             to: 'admin#update_privilege', as: :admin_update_privilege

    get    'mod-email',                    to: 'admin#admin_email', as: :moderator_email
    post   'mod-email',                    to: 'admin#send_admin_email', as: :send_moderator_email

    get    'audits',                       to: 'admin#audit_log', as: :audit_log

    get    'new-site',                     to: 'admin#new_site', as: :new_site
    post   'new-site',                     to: 'admin#create_site', as: :create_site

    get    'setup',                        to: 'admin#setup', as: :setup
    post   'setup',                        to: 'admin#setup_save', as: :setup_save

    get    'impersonate/stop',             to: 'admin#change_back', as: :stop_impersonating
    post   'impersonate/stop',             to: 'admin#verify_elevation', as: :verify_elevation
    post   'impersonate/:id',              to: 'admin#change_users', as: :impersonate
    get    'impersonate/:id',              to: 'admin#impersonate', as: :start_impersonating

    scope 'post-types' do
      root                                 to: 'post_types#index', as: :post_types
      get    'new',                        to: 'post_types#new', as: :new_post_type
      post   'new',                        to: 'post_types#create', as: :create_post_type
      get    ':id/edit',                   to: 'post_types#edit', as: :edit_post_type
      patch  ':id/edit',                   to: 'post_types#update', as: :update_post_type
    end
  end

  get    'close_reasons',                  to: 'close_reasons#index', as: :close_reasons
  get    'close_reasons/edit/:id',         to: 'close_reasons#edit', as: :close_reason
  patch  'close_reasons/edit/:id',         to: 'close_reasons#update', as: :update_close_reason
  get    'close_reasons/new',              to: 'close_reasons#new', as: :new_close_reason
  post   'close_reasons/new',              to: 'close_reasons#create', as: :create_close_reason

  scope  'admin/tag-sets' do
    root                                   to: 'tag_sets#index', as: :tag_sets
    get    'global',                       to: 'tag_sets#global', as: :global_tag_sets
    get    ':id',                          to: 'tag_sets#show', as: :tag_set
    post   ':id/edit',                     to: 'tag_sets#update', as: :update_tag_set
  end

  scope 'admin/licenses' do
    root                                   to: 'licenses#index', as: :licenses
    get    'new',                          to: 'licenses#new', as: :new_license
    post   'new',                          to: 'licenses#create', as: :create_license
    get    ':id/edit',                     to: 'licenses#edit', as: :edit_license
    patch  ':id/edit',                     to: 'licenses#update', as: :update_license
    post   ':id/toggle',                   to: 'licenses#toggle', as: :toggle_license
  end

  scope 'mod' do
    root                                   to: 'moderator#index', as: :moderator
    get    'deleted',                      to: 'moderator#recently_deleted_posts', as: :recently_deleted_posts
    get    'comments',                     to: 'moderator#recent_comments', as: :recent_comments
    get    'flags',                        to: 'flags#queue', as: :flag_queue
    get    'flags/handled',                to: 'flags#handled', as: :handled_flags
    get    'flags/escalated',              to: 'flags#escalated_queue', as: :escalated_flags
    delete 'users/destroy/:id',            to: 'users#destroy', as: :destroy_user
    get    'users/votes/:id',              to: 'moderator#user_vote_summary', as: :mod_vote_summary
    post   'flags/:id/resolve',            to: 'flags#resolve', as: :resolve_flag
    post   'flags/:id/escalate',           to: 'flags#escalate', as: :escalate_flag

    scope 'featured' do
      root                                 to: 'pinned_links#index', as: :pinned_links
      get   'new',                         to: 'pinned_links#new', as: :new_pinned_link
      post  'new',                         to: 'pinned_links#create', as: :create_pinned_link
      get   ':id/edit',                    to: 'pinned_links#edit', as: :edit_pinned_link
      patch ':id/edit',                    to: 'pinned_links#update', as: :update_pinned_link
    end
  end

  get    'questions/lottery',              to: 'questions#lottery', as: :questions_lottery

  scope 'posts/reactions' do
    root                                  to: 'reactions#index', as: :reactions
    get   ':id/edit',                     to: 'reactions#edit', as: :edit_reaction
    patch ':id/edit',                     to: 'reactions#update', as: :update_reaction
    get   'new',                          to: 'reactions#new', as: :new_reaction
    post  'new',                          to: 'reactions#create', as: :create_reaction

    post  'add',                          to: 'reactions#add', as: :add_reaction
    post  'retract',                      to: 'reactions#retract', as: :retract_reaction
  end

  scope 'posts' do
    scope 'suggested-edit' do
      get    ':id',           to: 'suggested_edit#show', as: :suggested_edit
      post   ':id/approve',   to: 'suggested_edit#approve', as: :suggested_edit_approve
      post   ':id/reject',    to: 'suggested_edit#reject', as: :suggested_edit_reject
    end

    get    'new/:post_type',               to: 'posts#new', as: :new_post
    get    'new/:post_type/respond/:parent', to: 'posts#new', as: :new_response
    get    'new/:post_type/:category',     to: 'posts#new', as: :new_category_post
    post   'new/:post_type',               to: 'posts#create', as: :create_post
    post   'new/:post_type/respond/:parent', to: 'posts#create', as: :create_response
    post   'new/:post_type/:category',     to: 'posts#create', as: :create_category_post
    get    'search',                       to: 'search#search', as: :search
    get    'promoted',                     to: 'moderator#promotions', as: :promoted_posts
    get    'types',                        to: 'post_types#list', as: :post_types_list
    post   'upload',                       to: 'posts#upload', as: :upload
    post   'save-draft',                   to: 'posts#save_draft', as: :save_draft
    post   'delete-draft',                 to: 'posts#delete_draft', as: :delete_draft

    get    ':id',                          to: 'posts#show', as: :post
    get    ':id/history',                  to: 'post_history#post', as: :post_history
    get    ':id/edit',                     to: 'posts#edit', as: :edit_post
    patch  ':id/edit',                     to: 'posts#update', as: :update_post
    post   ':id/close',                    to: 'posts#close', as: :close_post
    post   ':id/reopen',                   to: 'posts#reopen', as: :reopen_post
    post   ':id/delete',                   to: 'posts#delete', as: :delete_post
    post   ':id/restore',                  to: 'posts#restore', as: :restore_post
    post   ':id/category',                 to: 'posts#change_category', as: :change_category
    post   ':id/toggle_comments',          to: 'posts#toggle_comments', as: :post_comments_allowance_toggle
    post   ':id/lock',                     to: 'posts#lock', as: :post_lock
    post   ':id/unlock',                   to: 'posts#unlock', as: :post_unlock
    post   ':id/feature',                  to: 'posts#feature', as: :post_feature
    post   ':id/promote',                  to: 'moderator#nominate_promotion', as: :promote_post
    delete ':id/promote',                  to: 'moderator#remove_promotion', as: :remove_post_promotion

    get    ':id/:answer',                  to: 'posts#show', as: :answer_post
  end

  get    'policy/:slug',                   to: 'posts#document', as: :policy
  get    'help/:slug',                     to: 'posts#document', as: :help

  get    'tags',                           to: 'tags#index', as: :tags

  scope 'users/two-factor' do
    root                                   to: 'two_factor#tf_status', as: :two_factor_status
    post 'enable',                         to: 'two_factor#enable_2fa', as: :two_factor_enable
    get  'enable/code',                    to: 'two_factor#enable_code', as: :two_factor_enable_code
    post 'enable/code',                    to: 'two_factor#confirm_enable_code', as: :two_factor_confirm_enable
    get  'disable/code',                   to: 'two_factor#disable_code', as: :two_factor_disable_code
    post 'disable/code',                   to: 'two_factor#confirm_disable_code', as: :two_factor_confirm_disable

app/models/category.rb
class Category < ApplicationRecord
  include CommunityRelated

  has_many :category_post_types
  has_many :post_types, through: :category_post_types
  has_and_belongs_to_many :required_tags, class_name: 'Tag', join_table: 'categories_required_tags'
  has_and_belongs_to_many :topic_tags, class_name: 'Tag', join_table: 'categories_topic_tags'
  has_and_belongs_to_many :moderator_tags, class_name: 'Tag', join_table: 'categories_moderator_tags'
  has_many :posts
  belongs_to :tag_set
  belongs_to :license

  serialize :display_post_types, Array

  validates :name, uniqueness: { scope: [:community_id], case_sensitive: false }

  def new_posts_for?(user)
    key = "#{community_id}/#{user.id}/#{id}/last_visit"
    Rails.cache.fetch key, expires_in: 5.minutes do
      Rack::MiniProfiler.step "Redis: category last visit (#{key})" do
        activity_key = "#{community_id}/#{id}/last_activity"
        last_visit = RequestContext.redis.get(key)
        last_activity = RequestContext.redis.get(activity_key) || DateTime.parse
        last_visit.nil? || last_activity > DateTime.parse(last_visit)
      end
    end
  end

  def update_activity(last_activity)
    RequestContext.redis.set("#{community_id}/#{id}/last_activity", last_activity)
  end

  def self.by_lowercase_name(name)
    categories = Rails.cache.fetch 'categories/by_lowercase_name' do
      Category.all.to_h { |c| [c.name.downcase, c] }
    end
    categories[name]
  end

  def self.by_id(id)
    categories = Rails.cache.fetch 'categories/by_id' do
      Category.all.to_h { |c| [c.id, c] }
    end
    categories[id]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  include CommunityRelated

  has_and_belongs_to_many :posts
  has_many :children, class_name: 'Tag', foreign_key: :parent_id
  has_many :children_with_paths, class_name: 'TagWithPath', foreign_key: :parent_id
  has_many :post_history_tags
  belongs_to :tag_set
  belongs_to :parent, class_name: 'Tag', optional: true

  validates :excerpt, length: { maximum: 600 }, allow_blank: true
  validates :wiki_markdown, length: { maximum: 30_000 }, allow_blank: true
  validates :name, presence: true, format: { with: /[^ \t]+/, message: 'Tag names may not include spaces' }
  validate :parent_not_self
  validate :parent_not_own_child
  validates :name, uniqueness: { scope: [:tag_set_id], case_sensitive: false }

  def self.search(term)
    where('name LIKE ?', "%#{sanitize_sql_like(term)}%")
      .or(where('excerpt LIKE ?', "%#{sanitize_sql_like(term)}%"))
      .order(Arel.sql(sanitize_sql_array(['name LIKE ? DESC, name', "#{sanitize_sql_like(term)}%"])))
  end

  def all_children
    query = File.read(Rails.root.join('db/scripts/tag_children.sql'))
    query = query.gsub('$ParentId', id.to_s)
    ActiveRecord::Base.connection.execute(query).to_a.map(&:first)
  end

  def parent_chain
    Enumerator.new do |enum|
      parent_group = group
      until parent_group.nil?
        enum.yield parent_group
        parent_group = parent_group.group
      end
    end
  end

  private

  def parent_not_self
    return if parent_id.blank?

    if parent_id == id
      errors.add(:base, 'A tag cannot be its own parent.')
    end
  end

  def parent_not_own_child
    return if parent_id.blank?

    if all_children.include? parent_id
      errors.add(:base, "The #{parent.name} tag is already a child of this tag.")
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def category_sort_tags(tags, required_ids, topic_ids, moderator_ids)
    tags
      .to_a
      .sort_by do |t|
        [required_ids.include?(t.id) ? 0 : 1, moderator_ids.include?(t.id) ? 0 : 1,
         topic_ids.include?(t.id) ? 0 : 1, t.id]
      end
  end

  def tag_classes(tag, category)
    required_ids = category&.required_tag_ids
    moderator_ids = category&.moderator_tag_ids
    topic_ids = category&.topic_tag_ids
    required = required_ids&.include?(tag.id) ? 'is-filled' : ''
    topic = topic_ids&.include?(tag.id) ? 'is-outlined' : ''
    moderator = moderator_ids&.include?(tag.id) ? 'is-red is-outlined' : ''
    "badge is-tag #{required} #{topic} #{moderator}"
  end

  def post_ids_for_tags(tag_ids)
    sql = "SELECT post_id FROM posts_tags WHERE tag_id IN #{ApplicationRecord.sanitize_sql_in(tag_ids)}"
    ActiveRecord::Base.connection.execute(sql).to_a.flatten
  end
end

app/views/tags/_form.html.erb
<%= render 'posts/markdown_script' %>

<% if @tag.errors.any? %>
  <div class="notice is-danger">
    There were some errors while saving this tag:

    <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @tag, url: submit_path do |f| %>
  <% if submit_path == create_tag_path %>
    <div class="form-group">
      <%= f.label :name, 'Name', class: 'form-element' %>
      <span class="form-caption">
        Name of the tag
      </span>
      <%= f.text_field :name, class: 'form-element' %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :parent_id, 'Parent tag', class: 'form-element' %>
    <span class="form-caption">
      Optional. Select a parent tag to make this part of a tag hierarchy.
    </span>
    <%= f.select :parent_id, options_for_select(@tag.parent.present? ? [[@tag.parent.name, @tag.parent_id]] : [],
                                                selected: @tag.parent.present? ? @tag.parent_id : nil),
                 { include_blank: true }, class: "form-element js-tag-select",
                 data: { tag_set: @category.tag_set_id, use_ids: true, placeholder: "None" } %>
  </div>

  <div class="form-group">
    <%= f.label :excerpt, 'Usage guidance', class: 'form-element' %>
    <span class="form-caption">
      Short usage guidance for this tag. Will be cut off at 120 characters in the tags list, but displayed in full on
      the tag page.
    </span>
    <%= f.text_area :excerpt, class: 'form-element js-tag-excerpt', rows: 3 %>
    <span class="has-float-right has-font-size-caption js-character-count"
          data-target=".js-tag-excerpt" data-max="600">0 / 600</span>
  </div>

  <%= render 'shared/body_field', f: f, field_name: :wiki_markdown, field_label: 'Wiki', post: @tag do %>
    Full usage guidance and any other information you want people to know about this tag.
  <% end %>
  <div class="post-preview"></div>

  <%= f.submit 'Save', class: 'button is-filled' %>
<% end %>

app/views/tags/_list.html.erb
<div class="grid">
  <% required_ids = @category&.required_tag_ids %>
  <% moderator_ids = @category&.moderator_tag_ids %>
  <% topic_ids = @category&.topic_tag_ids %>

  <% ApplicationRecord.with_lax_group_rules do %>
    <% @tags.each do |tag| %>
      <% required = required_ids&.include?(tag.id) ? 'is-filled' : '' %>
      <% topic = topic_ids&.include?(tag.id) ? 'is-outlined' : '' %>
      <% moderator = moderator_ids&.include?(tag.id) ? 'is-red is-outlined' : '' %>
      <% classes = "badge is-tag #{required} #{topic} #{moderator}" %>
      <%= render 'tag', category: @category, tag: tag, classes: classes %>
    <% end %>
  <% end %>
</div>

app/views/tags/_tag.html.erb
<div class="grid--cell tag-cell <%= params[:hierarchical].present? ? 'is-12-sm is-6' : 'is-4-lg is-6-md is-12-sm' %>" data-ckb-list-item data-ckb-item-type="link">
  <% if tag.respond_to?(:path) && tag.path.present? %>
    <span class="has-font-size-caption">
      <% tag.path.split(' > ')[0..-2].each do |tag| %>
        <span class="badge is-tag is-small is-muted"><%= tag %></span> &raquo;
      <% end %>
    </span>
  <% end %>
  <%= link_to tag.name, tag_path(id: category.id, tag_id: tag.id), class: classes, 'data-ckb-item-link' => '' %>
  <span class="has-color-tertiary-900">&times;&nbsp;<%= tag.post_count %></span>
  <% if tag.excerpt.present? %>
    <p class="has-font-size-caption has-color-tertiary-900">
      <% splat = split_words_max_length(tag.excerpt, 120) %>
      <%= splat[0] %>
      <% if splat.size > 1 %>
        ...
      <% end %>
    </p>
  <% end %>
</div>

app/views/tags/category.html.erb
<% content_for :title, "Tags for #{@category.name}" %>

<h1>Tags used in <%= @category.name %></h1>

<% if current_user&.is_moderator %>
  <%= link_to 'New', new_tag_path(id: @category.id), class: 'button is-muted is-outlined' %>
<% end %>

<%= form_tag category_tags_path(@category), method: :get, class: 'form-inline' do %>
  <div class="form-group-horizontal">
    <div class="form-group">
      <%= label_tag :q, 'Search', class: 'form-element' %>
      <%= text_field_tag :q, params[:q], class: 'form-element' %>
    </div>
    <div class="actions has-padding-bottom-1">
      <button type="submit" class="button is-filled is-medium"><i class="fas fa-search"></i><span class="sr-only">Search</span></button>
    </div>
  </div>
<% end %>

<% unless params[:q].present? %>
  <div class="category-meta">
    <h3><%= pluralize(@count, 'tag') %></h3>
    <div class="button-list is-gutterless has-margin-2">
      <%= link_to 'Usage', category_tags_path(@category),
                  class: "button is-muted is-outlined #{request.query_parameters.size == 0 ? 'is-active' : ''}" %>
      <%= link_to 'Hierarchy', query_url(hierarchical: '1'),
                  class: "button is-muted is-outlined #{params[:hierarchical].present? ? 'is-active' : ''}" %>
      <%= link_to 'Missing Excerpt', query_url(no_excerpt: '1'),
                  class: "button is-muted is-outlined #{params[:no_excerpt].present? ? 'is-active' : ''}" %>
    </div>
  </div>
<% end %>

<%= render 'list' %>

<%= will_paginate @tags, renderer: BootstrapPagination::Rails %>

app/views/tags/children.html.erb
<% content_for :title, "Child tags of #{@tag.name}" %>

<h1>Child tags of <span class="<%= tag_classes(@tag, @category) %> is-large"><%= @tag.name %></span></h1>

<%= form_tag tag_children_path(id: @category.id, tag_id: @tag.id), method: :get, class: 'form-inline' do %>
  <div class="form-group-horizontal">
    <div class="form-group">
      <%= label_tag :q, 'Search', class: 'form-element' %>
      <%= text_field_tag :q, params[:q], class: 'form-element' %>
    </div>
    <div class="actions has-padding-bottom-1">
      <button type="submit" class="button is-filled is-medium"><i class="fas fa-search"></i><span class="sr-only">Search</span></button>
    </div>
  </div>
<% end %>

<% unless params[:q].present? %>
  <div class="category-meta">
    <h3><%= pluralize(@count, 'tag') %></h3>
    <div class="button-list is-gutterless has-margin-2">
      <%= link_to 'Usage', category_tags_path(@category),
                  class: "button is-muted is-outlined #{params[:hierarchical].nil? ? 'is-active' : ''}" %>
      <%= link_to 'Hierarchy', query_url(hierarchical: '1'),
                  class: "button is-muted is-outlined #{params[:hierarchical].present? ? 'is-active' : ''}" %>
    </div>
  </div>
<% end %>

<%= render 'list' %>

<%= will_paginate @tags, renderer: BootstrapPagination::Rails %>

app/views/tags/edit.html.erb
<% content_for :title, 'Edit tag' %>

<h1>
  Edit <span class="<%= @classes %> is-large"><%= @tag.name %></span>
</h1>

<%= render 'form', submit_path: update_tag_path(id: @category.id, tag_id: @tag.id) %>

app/views/tags/new.html.erb
<% content_for :title, 'Create tag' %>

<h1>
  Create <span class="<%= @classes %> is-large">Tag</span>
</h1>

<%= render 'form', submit_path: create_tag_path %>

app/views/tags/nuke_warning.html.erb
<p class="has-font-size-caption">
  <%= link_to tag_path(id: @category.id, tag_id: @tag.id) do %>
    &laquo; Back to tag
  <% end %>
</p>

<h1>Delete tag <%= @tag.name %></h1>

<div class="notice is-danger has-color-red-900">
  <p>
    Deleting a tag results in making it seem to have never existed in the first place. No record will be kept of the tag.
    This will:
  </p>

  <ul>
    <li>Remove all references to the tag, including post histories, suggested edits, and category special tags.</li>
    <li>Remove the tag from all posts currently using it, with no replacement.</li>
    <li>Remove the tag itself.</li>
  </ul>

  <p><strong>Please review posts using the tag before deleting it to ensure that posts are not left untagged.</strong></p>

  <p>This action will be logged.</p>
</div>

<%= link_to nuke_tag_path(id: @category.id, tag_id: @tag.id), class: 'button is-danger is-filled', method: :delete do %>
  I understand, delete <%= @tag.name %>
<% end %>

app/views/tags/select_merge.html.erb
<% content_for :title, "Merge tag into #{@tag.name}" %>

<h1 class="has-margin-0 has-margin-top-4">Merge tag into <%= @tag.name %></h1>
<p>
  You can select a tag here to merge it into this tag. All of the posts that have the tag you select will have it
  removed and replaced with this tag, and the selected tag will be deleted. Any children of the selected tag will
  not be deleted, but will revert to not having a parent. Sad face.
</p>

<div class="notice is-danger">
  <h4><i class="fas fa-exclamation-triangle"></i> Destructive action</h4>
  <p>
    Merging tags is a <strong>destructive action</strong>, meaning that once done it cannot be reversed. If you pick
    the wrong tag here and confirm it, not even a developer will be able to undo the merge.
  </p>
</div>

<%= form_tag merge_tag_path(id: @category.id, tag_id: @tag.id) do %>
  <div class="form-group">
    <%= select_tag :merge_with_id, options_for_select([]),
                   include_blank: true, class: "form-element js-tag-select",
                   data: { tag_set: @category.tag_set_id, use_ids: true } %>
  </div>

  <%= submit_tag 'Confirm Merge', class: 'button is-filled is-danger' %>
<% end %>

app/views/tags/show.html.erb
<% content_for :title, "Posts tagged #{@tag.name}" %>

<h1 class="has-margin-0 has-margin-top-4">
  Posts tagged <span class="<%= tag_classes(@tag, @category) %> is-large"><%= @tag.name %></span>
  <% if moderator? %>
    <a href="#" class="has-font-size-caption js-rename-tag h-m-r-2"
       data-category="<%= @category.id %>" data-tag="<%= @tag.id %>" data-name="<%= @tag.name %>">
      <i class="fas fa-pencil-alt" aria-label="Rename" title="Rename"></i>
    </a>
    <%= link_to select_tag_merge_path(id: @category.id, tag_id: @tag.id), class: 'has-font-size-caption h-m-r-2' do %>
      <i class="fas fa-project-diagram" aria-label="Merge" title="Merge"></i>
    <% end %>
  <% end %>
  <% if admin? %>
    <%= link_to nuke_tag_warning_path(id: @category.id, tag_id: @tag.id), class: 'has-font-size-caption h-m-r-2 is-red' do %>
      <i class="fas fa-trash" aria-label="Nuke" title="Nuke"></i>
    <% end %>
  <% end %>
</h1>
<p class="has-color-tertiary-900 has-font-weight-normal has-margin-0 has-font-family-brand">
  <% if @tag.parent_id.present? %>
      Subtag of <%= link_to @tag.parent.name, tag_path(id: @category.id, tag_id: @tag.parent_id),
                            class: tag_classes(@tag.parent, @category) %>
  <% end %>
  <% child_count = @tag.children.count %>
  <% if @tag.parent_id.present? && child_count > 0 %>
    &middot;
  <% end %>
  <% if child_count > 0 %>
    <%= link_to pluralize(child_count, 'child tag'), tag_children_path(id: @category.id, tag_id: @tag.id) %>
  <% end %>
</p>

<div class="widget">
  <div class="widget--body has-font-size-caption has-color-tertiary-900">
    <%= raw(sanitize(@tag.excerpt, scrubber: scrubber)&.gsub("\n", '<br/>')) %>
    <% unless @tag.excerpt.present? %>
      <p class="has-font-size-caption has-margin-0">
        <em>
          This tag doesn't have any usage information yet.
          <% if current_user&.privilege?('edit_tags') %>
            <%= link_to 'Help us create it', edit_tag_path(id: @category.id, tag_id: @tag.id) %>.
          <% end %>
        </em>
      </p>
    <% end %>
  </div>
  <div class="widget--body">
    <% if @tag.wiki.present? %>
      <% if @tag.wiki.length < 600 %>
      <%= raw(sanitize(@tag.wiki, scrubber: scrubber)) %>
      <% else %>
      <details>
        <summary>Tag Wiki</summary>
        <%= raw(sanitize(@tag.wiki, scrubber: scrubber)) %>
      </details>
      <% end %>
    <% end %>
    <% unless @tag.wiki.present? %>
      <p class="has-font-size-caption has-margin-0">
        <em>
          This tag doesn't have a detailed wiki yet.
          <% if current_user&.privilege?('edit_tags') %>
            <%= link_to 'Help us create it', edit_tag_path(id: @category.id, tag_id: @tag.id) %>.
          <% end %>
        </em>
      </p>
    <% end %>
  </div>
</div>

<% if current_user&.privilege?('edit_tags') %>
  <%= link_to 'Edit', edit_tag_path(id: @category.id, tag_id: @tag.id), class: 'button is-muted is-outlined' %>
<% end %>

<% post_count = @posts.count %>
<div class="has-color-tertiary-500 category-meta" title="<%= post_count %>">
  <div>
    <%= short_number_to_human post_count, precision: 1, significant: false %>
    <%= 'post'.pluralize(post_count) %>
    <%= link_to 'Subscribe',
                new_subscription_path(type: 'tag', qualifier: @tag.name, return_to: request.path),
                class: 'button is-outlined' %>
  </div>

  <div class="button-list is-gutterless has-margin-2">
    <%= link_to 'Tag Only', query_url(self: 1),
                class: "button is-muted is-outlined #{params[:self].present? ? 'is-active' : ''}" %>
    <%= link_to 'Tag + Children', tag_path(id: @category.id, tag_id: @tag.id),
                class: "button is-muted is-outlined #{params[:self].nil? ? 'is-active' : ''}" %>
  </div>
</div>

<div class="item-list">
  <% @posts.each do |post| %>
    <%= render 'posts/type_agnostic', post: post, show_type_tag: true, show_category_tag: true %>
  <% end %>
</div>

<div class="has-padding-top-4">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

<div class="has-padding-top-4">
  <%= link_to tag_path(id: @category.id, tag_id: @tag.id, format: 'rss') do %>
    <i class="fas fa-rss"></i> Tag RSS feed
  <% end %>
</div>