config/routes.rb
    get    'global',                       to: 'tag_sets#global', as: :global_tag_sets
    get    ':id',                          to: 'tag_sets#show', as: :tag_set
    post   ':id/edit',                     to: 'tag_sets#update', as: :update_tag_set
  end

  scope 'admin/licenses' do
    root                                   to: 'licenses#index', as: :licenses
    get    'new',                          to: 'licenses#new', as: :new_license
    post   'new',                          to: 'licenses#create', as: :create_license
    get    ':id/edit',                     to: 'licenses#edit', as: :edit_license
    patch  ':id/edit',                     to: 'licenses#update', as: :update_license
    post   ':id/toggle',                   to: 'licenses#toggle', as: :toggle_license
  end

  scope 'mod' do
    root                                   to: 'moderator#index', as: :moderator
    get    'deleted',                      to: 'moderator#recently_deleted_posts', as: :recently_deleted_posts
    get    'comments',                     to: 'moderator#recent_comments', as: :recent_comments
    get    'flags',                        to: 'flags#queue', as: :flag_queue
    get    'flags/handled',                to: 'flags#handled', as: :handled_flags
    get    'flags/escalated',              to: 'flags#escalated_queue', as: :escalated_flags
    delete 'users/destroy/:id',            to: 'users#destroy', as: :destroy_user
    get    'users/votes/:id',              to: 'moderator#user_vote_summary', as: :mod_vote_summary
    post   'flags/:id/resolve',            to: 'flags#resolve', as: :resolve_flag
    post   'flags/:id/escalate',           to: 'flags#escalate', as: :escalate_flag

    scope 'featured' do
      root                                 to: 'pinned_links#index', as: :pinned_links
      get   'new',                         to: 'pinned_links#new', as: :new_pinned_link
      post  'new',                         to: 'pinned_links#create', as: :create_pinned_link
      get   ':id/edit',                    to: 'pinned_links#edit', as: :edit_pinned_link
      patch ':id/edit',                    to: 'pinned_links#update', as: :update_pinned_link
    end
  end

  get    'questions/lottery',              to: 'questions#lottery', as: :questions_lottery

  scope 'posts/reactions' do
    root                                  to: 'reactions#index', as: :reactions
    get   ':id/edit',                     to: 'reactions#edit', as: :edit_reaction
    patch ':id/edit',                     to: 'reactions#update', as: :update_reaction
    get   'new',                          to: 'reactions#new', as: :new_reaction
    post  'new',                          to: 'reactions#create', as: :create_reaction

    post  'add',                          to: 'reactions#add', as: :add_reaction
    post  'retract',                      to: 'reactions#retract', as: :retract_reaction
  end

  scope 'posts' do
    scope 'suggested-edit' do
      get    ':id',           to: 'suggested_edit#show', as: :suggested_edit
      post   ':id/approve',   to: 'suggested_edit#approve', as: :suggested_edit_approve
      post   ':id/reject',    to: 'suggested_edit#reject', as: :suggested_edit_reject
    end

    get    'new/:post_type',               to: 'posts#new', as: :new_post
    get    'new/:post_type/respond/:parent', to: 'posts#new', as: :new_response
    get    'new/:post_type/:category',     to: 'posts#new', as: :new_category_post
    post   'new/:post_type',               to: 'posts#create', as: :create_post
    post   'new/:post_type/respond/:parent', to: 'posts#create', as: :create_response
    post   'new/:post_type/:category',     to: 'posts#create', as: :create_category_post
    get    'search',                       to: 'search#search', as: :search
    get    'promoted',                     to: 'moderator#promotions', as: :promoted_posts
    get    'types',                        to: 'post_types#list', as: :post_types_list
    post   'upload',                       to: 'posts#upload', as: :upload
    post   'save-draft',                   to: 'posts#save_draft', as: :save_draft
    post   'delete-draft',                 to: 'posts#delete_draft', as: :delete_draft

    get    ':id',                          to: 'posts#show', as: :post
    get    ':id/history',                  to: 'post_history#post', as: :post_history
    get    ':id/edit',                     to: 'posts#edit', as: :edit_post
    patch  ':id/edit',                     to: 'posts#update', as: :update_post
    post   ':id/close',                    to: 'posts#close', as: :close_post
    post   ':id/reopen',                   to: 'posts#reopen', as: :reopen_post
    post   ':id/delete',                   to: 'posts#delete', as: :delete_post
    post   ':id/restore',                  to: 'posts#restore', as: :restore_post
    post   ':id/category',                 to: 'posts#change_category', as: :change_category
    post   ':id/toggle_comments',          to: 'posts#toggle_comments', as: :post_comments_allowance_toggle
    post   ':id/lock',                     to: 'posts#lock', as: :post_lock
    post   ':id/unlock',                   to: 'posts#unlock', as: :post_unlock
    post   ':id/feature',                  to: 'posts#feature', as: :post_feature
    post   ':id/promote',                  to: 'moderator#nominate_promotion', as: :promote_post
    delete ':id/promote',                  to: 'moderator#remove_promotion', as: :remove_post_promotion

    get    ':id/:answer',                  to: 'posts#show', as: :answer_post
  end

  get    'policy/:slug',                   to: 'posts#document', as: :policy
  get    'help/:slug',                     to: 'posts#document', as: :help

  get    'tags',                           to: 'tags#index', as: :tags

  scope 'users/two-factor' do
    root                                   to: 'two_factor#tf_status', as: :two_factor_status
    post 'enable',                         to: 'two_factor#enable_2fa', as: :two_factor_enable
    get  'enable/code',                    to: 'two_factor#enable_code', as: :two_factor_enable_code
    post 'enable/code',                    to: 'two_factor#confirm_enable_code', as: :two_factor_confirm_enable
    get  'disable/code',                   to: 'two_factor#disable_code', as: :two_factor_disable_code
    post 'disable/code',                   to: 'two_factor#confirm_disable_code', as: :two_factor_confirm_disable
    post 'disable/link-email',             to: 'two_factor#send_disable_email', as: :two_factor_send_disable_email
    get  'disable/link/:token',            to: 'two_factor#disable_link', as: :two_factor_disable_link
    post 'disable/link',                   to: 'two_factor#confirm_disable_link', as: :two_factor_confirm_disable_link
  end

  scope  'users' do
    root                                to: 'users#index', as: :users
    get    '/stack-redirect',           to: 'users#stack_redirect', as: :stack_redirect
    post   '/claim-content',            to: 'users#transfer_se_content', as: :claim_stack_content
    get    '/mobile-login',             to: 'users#qr_login_code', as: :qr_login_code
    get    '/mobile-login/:token',      to: 'users#do_qr_login', as: :qr_login
    get    '/me',                       to: 'users#me', as: :users_me
    get    '/me/preferences',           to: 'users#preferences', as: :user_preferences
    post   '/me/preferences',           to: 'users#set_preference', as: :set_user_preference
    get    '/me/notifications',         to: 'notifications#index', as: :notifications
    get    '/edit/profile',             to: 'users#edit_profile', as: :edit_user_profile
    patch  '/edit/profile',             to: 'users#update_profile', as: :update_user_profile
    get    '/me/vote-summary',          to: 'users#my_vote_summary', as: :my_vote_summary
    get    '/avatar/:letter/:color/:size', to: 'users#specific_avatar', as: :specific_auto_avatar
    get    '/:id',                      to: 'users#show', as: :user
    get    '/:id/flags',                to: 'flags#history', as: :flag_history
    get    '/:id/activity',             to: 'users#activity', as: :user_activity
    get    '/:id/mod',                  to: 'users#mod', as: :mod_user
    get    '/:id/posts',                to: 'users#posts', as: :user_posts
    get    '/:id/vote-summary',         to: 'users#vote_summary', as: :vote_summary
    get    '/:id/mod/privileges',       to: 'users#mod_privileges', as: :user_privileges
    post   '/:id/mod/privileges',       to: 'users#mod_privilege_action', as: :user_privilege_action
    post   '/:id/mod/toggle-role',      to: 'users#role_toggle', as: :toggle_user_role
    get    '/:id/mod/annotations',      to: 'users#annotations', as: :user_annotations
    post   '/:id/mod/annotations',      to: 'users#annotate', as: :annotate_user
    get    '/:id/mod/activity-log',     to: 'users#full_log', as: :full_user_log
    post   '/:id/hellban',              to: 'admin#hellban', as: :hellban_user
    get    '/:id/avatar/:size',         to: 'users#avatar', as: :user_auto_avatar
  end

  post   'notifications/:id/read',         to: 'notifications#read', as: :read_notifications
  post   'notifications/read_all',         to: 'notifications#read_all', as: :read_all_notifications

  post   'votes/new',                      to: 'votes#create', as: :create_vote
  delete 'votes/:id',                      to: 'votes#destroy', as: :destroy_vote

  post   'answers/:id/convert',            to: 'answers#convert_to_comment', as: :convert_to_comment

  post   'flags/new',                      to: 'flags#new', as: :new_flag

  scope 'comments' do
    post   'new',                          to: 'comments#create_thread', as: :create_comment_thread
    get    'thread/:id/pingable',          to: 'comments#pingable', as: :thread_pingable
    post   'thread/:id/new',               to: 'comments#create', as: :create_comment

app/models/category.rb
class Category < ApplicationRecord
  include CommunityRelated

  has_many :category_post_types
  has_many :post_types, through: :category_post_types
  has_and_belongs_to_many :required_tags, class_name: 'Tag', join_table: 'categories_required_tags'
  has_and_belongs_to_many :topic_tags, class_name: 'Tag', join_table: 'categories_topic_tags'
  has_and_belongs_to_many :moderator_tags, class_name: 'Tag', join_table: 'categories_moderator_tags'
  has_many :posts
  belongs_to :tag_set
  belongs_to :license

  serialize :display_post_types, Array

  validates :name, uniqueness: { scope: [:community_id], case_sensitive: false }

  def new_posts_for?(user)
    key = "#{community_id}/#{user.id}/#{id}/last_visit"
    Rails.cache.fetch key, expires_in: 5.minutes do
      Rack::MiniProfiler.step "Redis: category last visit (#{key})" do
        activity_key = "#{community_id}/#{id}/last_activity"
        last_visit = RequestContext.redis.get(key)
        last_activity = RequestContext.redis.get(activity_key) || DateTime.parse
        last_visit.nil? || last_activity > DateTime.parse(last_visit)
      end
    end
  end

  def update_activity(last_activity)
    RequestContext.redis.set("#{community_id}/#{id}/last_activity", last_activity)
  end

  def self.by_lowercase_name(name)
    categories = Rails.cache.fetch 'categories/by_lowercase_name' do
      Category.all.to_h { |c| [c.name.downcase, c] }
    end
    categories[name]
  end

  def self.by_id(id)
    categories = Rails.cache.fetch 'categories/by_id' do
      Category.all.to_h { |c| [c.id, c] }
    end
    categories[id]
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def active?(category)
    current_category
    current_page?(category_url(category)) || (category.is_homepage && current_page?(root_url)) ||
      (defined?(@current_category) && @current_category&.id == category.id)
  end

  def expandable?
    (defined?(@category) && !@category&.id.nil? && !current_page?(new_category_url)) ||
      (defined?(@post) && !@post&.category.nil?) ||
      (defined?(@question) && !@question&.category.nil?) ||
      (defined?(@article) && !@article&.category.nil?)
  end

  def current_category
    @current_category ||= if defined?(@category) && !@category&.id.nil?
                            @category
                          elsif defined?(@post) && !@post&.category.nil?
                            @post.category
                          elsif defined?(@question) && !@question&.category.nil?
                            @question.category
                          elsif defined?(@article) && !@article&.category.nil?
                            @article.category
                          end
  end
end

app/views/categories/_form.html.erb
<%= form_for @category, url: submit_path, method: :post do |f| %>
  <details open>
    <summary>
      Basic Information
      <span class="subheading">Name, description</span>
    </summary>

    <div class="form-group">
      <%= f.label :name, class: 'form-element' %>
      <span class="form-caption">This will be public, so make it something simple and recognisable.</span>
      <%= f.text_field :name, class: 'form-element' %>
    </div>

    <div class="form-group">
      <%= f.label :short_wiki, class: 'form-element' %>
      <span class="form-caption">A short description of what this category is for. Markdown supported.</span>
      <%= f.text_area :short_wiki, class: 'form-element is-small' %>
    </div>
  </details>

  <details>
    <summary>
      Posting
      <span class="subheading">Post types, tag set</span>
    </summary>

    <div class="form-group">
      <%= f.label :display_post_types, 'Listed post types', class: 'form-element' %>
      <span class="form-caption">
        These post types will be displayed on the category's homepage. For a Q&A category, you might only want to show questions.
      </span>
      <%= f.select :display_post_types, options_for_select(PostType.mapping.to_a, selected: @category.display_post_types),
                   { include_blank: true }, multiple: true, class: 'form-element' %>
    </div>

    <% if @category.id.present? %>
      <div class="form-group">
        <%= f.label :post_type_ids, 'Allowed post types', class: 'form-element' %>
        <div class="form-caption h-m-t-1">Only these post types will be allowed in this category.</div>
        <%= link_to edit_category_post_types_path(@category) do %>
          Edit allowed post types &raquo;
        <% end %>
      </div>
    <% else %>
      <p>You'll be able to set up allowed post types in this category once you've created it.</p>
    <% end %>

    <div class="form-group">
      <%= f.label :tag_set_id, 'Tag set', class: 'form-element' %>
      <span class="form-caption">Which tag set may posts in this category draw from?</span>
      <%= f.select :tag_set_id, options_for_select(TagSet.all.map { |ts|  [ts.name, ts.id] }, selected: @category.tag_set_id),
                   { include_blank: true }, class: 'form-element js-category-tag-set-select' %>
    </div>
  </details>

  <details>
    <summary>
      Permissions
      <span class="subheading">Trust levels, licensing</span>
    </summary>

    <div class="form-group">
      <%= f.label :min_trust_level, 'Minimum posting trust level', class: 'form-element' %>
      <span class="form-caption">
        Users must have at least this trust level to post in this category. Leave blank to allow
        anyone to post.
      </span>
      <%= f.select :min_trust_level, options_for_select(Ability.trust_levels.invert.each_pair, selected: @category.min_trust_level),
                   {}, class: 'form-element' %>
    </div>

    <div class="form-group">
      <%= f.label :min_view_trust_level, 'Minimum visible trust level', class: 'form-element' %>
      <span class="form-caption">
        Users under this trust level cannot see that this category exists. Leave blank to leave the category public.
        This can be different (higher or lower) than the minimum posting trust level.
      </span>
      <%= f.select :min_view_trust_level, options_for_select(Ability.trust_levels.invert.each_pair, selected: @category.min_view_trust_level),
                   {}, class: 'form-element' %>
    </div>

    <div class="form-group">
      <%= f.label :license_id, 'Default license', class: 'form-element' %>
      <span class="form-caption">
        Posts in this category will default to this license. Users can still select a different license
        if they choose to.
      </span>
      <%= f.select :license_id, options_for_select(License.enabled.default_order.map { |l| [l.name, l.id] },
                                                   selected: @category.license_id), {}, class: 'form-element' %>
    </div>
  </details>

  <details>
    <summary>
      Display
      <span class="subheading">Homepage, post button, colors, ordering</span>
    </summary>

    <div class="form-group">
      <%= f.label :button_text, 'Post button text', class: 'form-element' %>
      <span class="form-caption">Customise the text on the "Create Post" button. Leave blank for default.</span>
      <%= f.text_field :button_text, class: 'form-element' %>
    </div>

    <div class="form-group">
      <%= f.check_box :is_homepage, class: 'form-checkbox-element' %>
      <%= f.label :is_homepage, 'Set as homepage?' %>
      <span class="form-caption">Tick this box to set this category as the site homepage.</span>
    </div>

    <div class="form-group">
      <%= f.label :color_code, 'Header color', class: 'form-element' %>
      <span class="form-caption">Select a color to be used for the header within this category. Leave empty for site-wide default.</span>
      <%= f.select :color_code, options_for_select(['turquoise', 'green', 'blue', 'darkblue', 'purple', 'gray', 'bluegray', 'yellow', 'orange', 'pink', 'red'], selected: @category.color_code),
                   { include_blank: true }, class: 'form-element' %>
    </div>

    <div class="form-group">
      <%= f.label :sequence, class: 'form-element' %>
      <span class="form-caption">
      The order in which this category will appear in the header and on the category list page. Higher numbers
      appear later.
    </span>
      <%= f.number_field :sequence, class: 'form-element' %>
    </div>
  </details>

  <details>
    <summary>
      Help &amp; Guidance
      <span class="subheading">Guidance overrides</span>
    </summary>

    <div class="form-group">
      <%= f.label :asking_guidance_override, class: 'form-element' %>
      <span class="form-caption">
      This field overrides the default asking guidance and is shown when a new post is created. Leave blank to use site-default.
    </span>
      <%= f.text_area :asking_guidance_override, class: 'form-element' %>
    </div>

    <div class="form-group">
      <%= f.label :answering_guidance_override, class: 'form-element' %>
      <span class="form-caption">
      This field overrides the default answering guidance and is shown when a new answer is created. Leave blank to use site-default.
    </span>
      <%= f.text_area :answering_guidance_override, class: 'form-element' %>
    </div>
  </details>

  <details>
    <summary>
      Sharing &amp; Promotion
      <span class="subheading">Hot posts, advertising</span>
    </summary>

    <div class="form-group">
      <%= f.label :use_for_hot_posts, class: 'form-element' %>
      <span class="form-caption">
      Whether the posts of this category are eligible to be selected as hot posts.
    </span>
      <%= f.select :use_for_hot_posts, options_for_select([['yes', true], ['no', false]], selected: @category.use_for_hot_posts),
                   {}, class: 'form-element' %>
    </div>

    <div class="form-group">
      <%= f.label :use_for_advertisement, class: 'form-element' %>
      <span class="form-caption">
      Whether the posts of this category are eligible to be selected as random advertisement.
    </span>
      <%= f.select :use_for_advertisement, options_for_select([['yes', true], ['no', false]], selected: @category.use_for_advertisement),
                   {}, class: 'form-element' %>
    </div>
  </details>

  <details>
    <summary>
      Tagging
      <span class="subheading">Required, topic, moderator tags</span>
    </summary>

    <div class="form-group js-category-tags-group">
      <%= f.label :required_tag_ids, 'Required tags', class: 'form-element' %>
      <span class="form-caption js-tags-group-caption">
      <span data-state="present" style="<%= @category.tag_set.nil? ? 'display: none' : '' %>">
        Required tags for this category - every post will be required to have one of these tags.
      </span>
      <span data-state="absent" style="<%= @category.tag_set.nil? ? '' : 'display: none' %>">
        Select a tag set first.
      </span>
    </span>
      <% disabled = @category.tag_set.nil? %>
      <%= f.select :required_tag_ids, options_for_select(@category.required_tags.map { |t| [t.name, t.id] },
                                                         selected: @category.required_tag_ids),
                   { include_blank: true }, multiple: true, class: 'form-element js-tag-select js-required-tags',
                   data: { tag_set: @category.tag_set&.id, create: 'false', use_ids: 'true' }, disabled: disabled %>
    </div>

    <div class="form-group js-category-tags-group">
      <%= f.label :topic_tag_ids, 'Topic tags', class: 'form-element' %>
      <span class="form-caption js-tags-group-caption">
      <span data-state="present" style="<%= @category.tag_set.nil? ? 'display: none' : '' %>">
        Tags that will be highlighted as the most important tag on a question.
        <a href="javascript:void(0)" class="js-add-required-topic">Add all required tags</a>
      </span>
      <span data-state="absent" style="<%= @category.tag_set.nil? ? '' : 'display: none' %>">
        Select a tag set first.
      </span>
    </span>

      <%= f.select :topic_tag_ids, options_for_select(@category.topic_tags.map { |t| [t.name, t.id] },
                                                      selected: @category.topic_tag_ids),
                   { include_blank: true }, multiple: true, class: 'form-element js-tag-select js-topic-tags',
                   data: { tag_set: @category.tag_set&.id, create: 'false', use_ids: 'true' }, disabled: disabled %>
    </div>

    <div class="form-group js-category-tags-group">
      <%= f.label :moderator_tag_ids, 'Moderator-only tags', class: 'form-element' %>
      <span class="form-caption js-tags-group-caption">
      <span data-state="present" style="<%= @category.tag_set.nil? ? 'display: none' : '' %>">
        Tags that only moderators can use in this category.
      </span>
      <span data-state="absent" style="<%= @category.tag_set.nil? ? '' : 'display: none' %>">
        Select a tag set first.
      </span>
    </span>

      <%= f.select :moderator_tag_ids, options_for_select(@category.moderator_tags.map { |t| [t.name, t.id] },
                                                          selected: @category.moderator_tag_ids),
                   { include_blank: true }, multiple: true, class: 'form-element js-tag-select js-moderator-tags',
                   data: { tag_set: @category.tag_set&.id, create: 'false', use_ids: 'true' }, disabled: disabled %>
    </div>
  </details>

  <div class="has-margin-top-2">
    <%= f.submit 'Save', class: 'button is-filled' %>
  </div>
<% end %>

app/views/categories/category_post_types.html.erb
<p class="has-font-size-caption">
  <%= link_to edit_category_path(@category) do %>
    &laquo; Back to category edit
  <% end %>
</p>
<h1>Allowed post types for <%= @category.name %></h1>
<p class="has-font-size-caption">
  Only post types listed here are allowed to be posted in this category. Not all will be displayed as available options
  when creating a post; to configure that, go back to category settings. You must configure reputation awards for each
  post type.
</p>

<div class="js-cpt-list">
  <% @category_post_types.each do |cpt| %>
    <%= render 'category_post_type_edit', cpt: cpt %>
  <% end %>
</div>

<h3>Add post type</h3>
<div class="widget">
  <div class="grid has-padding-2 ai-c">
    <div class="grid--cell is-6 is-12-sm">
      <%= label_tag 'post-type-new', 'Post type' %>
      <%= select_tag 'post-type-new', options_for_select(PostType.all.map { |pt| [pt.name, pt.id] }), include_blank: true,
                     class: 'form-element js-cpt-post-type' %>
    </div>
    <div class="grid--cell is-2 is-6-sm">
      <%= label_tag 'upvote-rep-new', 'Upvote rep' %>
      <%= number_field_tag 'upvote-rep-new', nil, class: 'form-element js-cpt-upvote-rep' %>
    </div>
    <div class="grid--cell is-2 is-6-sm">
      <%= label_tag 'downvote-rep-new', 'Downvote rep' %>
      <%= number_field_tag 'downvote-rep-new', nil, class: 'form-element js-cpt-downvote-rep' %>
    </div>
    <div class="grid--cell is-2 is-12-sm">
      <button type="button" class="add-cpt js-update-cpt button is-filled" data-category="<%= @category.id %>">
        Add
      </button>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<p>
  If you need to change something about one of your site's categories, this is the place to do it.
</p>

<%= render 'form', submit_path: update_category_path(@category) %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |cat| %>
  <% next unless (current_user&.trust_level || 0) >= (cat.min_view_trust_level || -1) %>
  <div class="widget">
    <div class="widget--body">
      <h3><%= cat.name %></h3>
      <% if cat.short_wiki.present? %>
        <%= raw(sanitize(render_markdown(cat.short_wiki), scrubber: scrubber)) %>
      <% end %>
      <% post_count = cat.posts.undeleted.count %>
      <span class="has-color-tertiary-500" title="<%= post_count %>">
        <%= short_number_to_human post_count, precision: 1, significant: false %>
        <%= 'post'.pluralize(post_count) %>
      </span>
    </div>
    <div class="widget--footer">
      <%= link_to category_path(cat), class: 'button is-filled' do %>
        See posts &raquo;
      <% end %>
      <% if current_user&.is_admin %>
        <%= link_to 'Edit', edit_category_path(cat), class: 'button is-outlined' %>
      <% end %>
    </div>
  </div>
<% end %>

<% if current_user&.is_admin %>
  <%= link_to new_category_path, class: 'button is-outlined' do %>
    Add new category &raquo;
  <% end %>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<p>
  If the standard two Q&amp;A categories aren't enough for your site, you can add a new category here.
</p>

<%= render 'form', submit_path: create_category_path %>

app/views/categories/post_types.html.erb
<h1>What kind of post?</h1>
<p class="has-font-size-larger has-color-tertiary-500">
  This category has more than one type of post available. Pick a post type to get started.
</p>

<% @post_types.each do |pt| %>
  <h3><%= link_to pt.name.underscore.humanize, new_category_post_path(post_type: pt, category: @category) %></h3>
  <p class="has-color-tertiary-500"><%= pt.description %></p>
  <hr/>
<% end %>

app/views/categories/show.html.erb
<% content_for :title, @category.name %>

<% if @category.short_wiki %>
  <div class="category--description open" data-category-id="<%= @category.id %>">
    <div class="category--collapse">
      <% cache [@category, 'description-rendered'] do %>
        <%= raw(sanitize(render_markdown(@category.short_wiki), scrubber: scrubber)) %>
      <% end %>
    </div>
  </div>
<% end %>

<% post_count = @posts.count %>
<div class="has-color-tertiary-500 category-meta" title="<%= post_count %>">
  <div>
    <%= short_number_to_human post_count, precision: 1, significant: false %>
    <%= 'post'.pluralize(post_count) %> &middot;

    <% if current_user&.is_admin %>
      <%= link_to 'Edit Category', edit_category_path(@category) %>
      &middot;
    <% end %>

    <%= link_to 'Subscribe',
                new_subscription_path(type: 'category', qualifier: @category.id, return_to: request.path),
                class: 'button is-outlined' %>
  </div>

  <div class="button-list is-gutterless has-margin-2">
    <%= link_to 'Activity', query_url(sort: 'activity'),
                class: "button is-muted is-outlined #{(params[:sort].nil?) && !current_page?(questions_lottery_path) ||
                    params[:sort] == 'activity' ? 'is-active' : ''}",
                title: 'most recent changes: new posts, edits, close/open, delete/undelete' %>
    <%= link_to 'Age', query_url(sort: 'age'),
                class: "button is-muted is-outlined #{params[:sort] == 'age' ? 'is-active' : ''}",
                title: 'newest posts (ignores other activity)' %>
    <%= link_to 'Score', query_url(sort: 'score'),
                class: "button is-muted is-outlined #{params[:sort] == 'score' ? 'is-active' : ''}",
                title: 'highest score first (not the same as net votes)' %>
    <% if SiteSetting['AllowContentTransfer'] %>
      <%= link_to 'Native', query_url(sort: 'native'),
                  class: "button is-muted is-outlined #{params[:sort] == 'native' ? 'is-active' : ''}",
                  title: 'exclude imported posts' %>
    <% end %>
    <% if @category.name == 'Q&A' %>
      <%= link_to 'Random', query_url(sort: 'lottery'),
                  class: "button is-muted is-outlined #{params[:sort] == 'lottery' ? 'is-active' : ''}",
                  title: 'random set of questions, usually older ones' %>
    <% end %>
  </div>
</div>

<div class="item-list">
  <% @posts.each do |post| %>
    <%= render 'posts/type_agnostic', post: post %>
  <% end %>
</div>

<div class="has-padding-top-4">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

<div class="has-padding-top-4">
  <%= link_to category_feed_path(@category, format: 'rss') do %>
    <i class="fas fa-rss"></i> Category RSS feed
  <% end %>
</div>