config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get  'users/2fa/login',                to: 'users/sessions#verify_2fa', as: :login_verify_2fa
    post 'users/2fa/login',                to: 'users/sessions#verify_code', as: :login_verify_code
  end

  root                                     to: 'categories#homepage'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  
  
  scope 'admin' do
    root                                   to: 'admin#index', as: :admin
    get    'errors',                       to: 'admin#error_reports', as: :admin_error_reports

    get    'settings',                     to: 'site_settings#index', as: :site_settings
    get    'settings/global',              to: 'site_settings#global', as: :global_settings
    get    'settings/:name',               to: 'site_settings#show', as: :site_setting
    post   'settings/:name',               to: 'site_settings#update', as: :update_site_setting

    delete 'users/delete/:id',             to: 'users#soft_delete', as: :soft_delete_user

    get    'privileges',                   to: 'admin#privileges', as: :admin_privileges
    get    'privileges/:name',             to: 'admin#show_privilege', as: :admin_privilege
    post   'privileges/:name',             to: 'admin#update_privilege', as: :admin_update_privilege

    get    'mod-email',                    to: 'admin#admin_email', as: :moderator_email
    post   'mod-email',                    to: 'admin#send_admin_email', as: :send_moderator_email

    get    'audits',                       to: 'admin#audit_log', as: :audit_log

    get    'new-site',                     to: 'admin#new_site', as: :new_site
    post   'new-site',                     to: 'admin#create_site', as: :create_site

    get    'setup',                        to: 'admin#setup', as: :setup
    post   'setup',                        to: 'admin#setup_save', as: :setup_save

    get    'impersonate/stop',             to: 'admin#change_back', as: :stop_impersonating
    post   'impersonate/stop',             to: 'admin#verify_elevation', as: :verify_elevation
    post   'impersonate/:id',              to: 'admin#change_users', as: :impersonate
    get    'impersonate/:id',              to: 'admin#impersonate', as: :start_impersonating

    scope 'post-types' do
      root                                 to: 'post_types#index', as: :post_types
      get    'new',                        to: 'post_types#new', as: :new_post_type
      post   'new',                        to: 'post_types#create', as: :create_post_type
      get    ':id/edit',                   to: 'post_types#edit', as: :edit_post_type
      patch  ':id/edit',                   to: 'post_types#update', as: :update_post_type
    end
  end

  get    'close_reasons',                  to: 'close_reasons#index', as: :close_reasons
  get    'close_reasons/edit/:id',         to: 'close_reasons#edit', as: :close_reason
  patch  'close_reasons/edit/:id',         to: 'close_reasons#update', as: :update_close_reason
  get    'close_reasons/new',              to: 'close_reasons#new', as: :new_close_reason
  post   'close_reasons/new',              to: 'close_reasons#create', as: :create_close_reason

  scope  'admin/tag-sets' do
    root                                   to: 'tag_sets#index', as: :tag_sets
    get    'global',                       to: 'tag_sets#global', as: :global_tag_sets
    get    ':id',                          to: 'tag_sets#show', as: :tag_set
    post   ':id/edit',                     to: 'tag_sets#update', as: :update_tag_set
  end

  scope 'admin/licenses' do
    root                                   to: 'licenses#index', as: :licenses
    get    'new',                          to: 'licenses#new', as: :new_license
    post   'new',                          to: 'licenses#create', as: :create_license
    get    ':id/edit',                     to: 'licenses#edit', as: :edit_license
    patch  ':id/edit',                     to: 'licenses#update', as: :update_license
    post   ':id/toggle',                   to: 'licenses#toggle', as: :toggle_license
  end

  scope 'mod' do
    root                                   to: 'moderator#index', as: :moderator
    get    'deleted',                      to: 'moderator#recently_deleted_posts', as: :recently_deleted_posts
    get    'comments',                     to: 'moderator#recent_comments', as: :recent_comments
    get    'flags',                        to: 'flags#queue', as: :flag_queue
    get    'flags/handled',                to: 'flags#handled', as: :handled_flags
    get    'flags/escalated',              to: 'flags#escalated_queue', as: :escalated_flags
    delete 'users/destroy/:id',            to: 'users#destroy', as: :destroy_user
    get    'users/votes/:id',              to: 'moderator#user_vote_summary', as: :mod_vote_summary
    post   'flags/:id/resolve',            to: 'flags#resolve', as: :resolve_flag
    post   'flags/:id/escalate',           to: 'flags#escalate', as: :escalate_flag

    scope 'featured' do
      root                                 to: 'pinned_links#index', as: :pinned_links
      get   'new',                         to: 'pinned_links#new', as: :new_pinned_link
      post  'new',                         to: 'pinned_links#create', as: :create_pinned_link
      get   ':id/edit',                    to: 'pinned_links#edit', as: :edit_pinned_link
      patch ':id/edit',                    to: 'pinned_links#update', as: :update_pinned_link
    end
  end

  get    'questions/lottery',              to: 'questions#lottery', as: :questions_lottery

  scope 'posts/reactions' do
    root                                  to: 'reactions#index', as: :reactions
    get   ':id/edit',                     to: 'reactions#edit', as: :edit_reaction
    patch ':id/edit',                     to: 'reactions#update', as: :update_reaction
    get   'new',                          to: 'reactions#new', as: :new_reaction
    post  'new',                          to: 'reactions#create', as: :create_reaction

    post  'add',                          to: 'reactions#add', as: :add_reaction
    post  'retract',                      to: 'reactions#retract', as: :retract_reaction
  end

  scope 'posts' do
    scope 'suggested-edit' do
      get    ':id',           to: 'suggested_edit#show', as: :suggested_edit
      post   ':id/approve',   to: 'suggested_edit#approve', as: :suggested_edit_approve
      post   ':id/reject',    to: 'suggested_edit#reject', as: :suggested_edit_reject
    end

    get    'new/:post_type',               to: 'posts#new', as: :new_post
    get    'new/:post_type/respond/:parent', to: 'posts#new', as: :new_response
    get    'new/:post_type/:category',     to: 'posts#new', as: :new_category_post
    post   'new/:post_type',               to: 'posts#create', as: :create_post
    post   'new/:post_type/respond/:parent', to: 'posts#create', as: :create_response
    post   'new/:post_type/:category',     to: 'posts#create', as: :create_category_post
    get    'search',                       to: 'search#search', as: :search
    get    'promoted',                     to: 'moderator#promotions', as: :promoted_posts
    get    'types',                        to: 'post_types#list', as: :post_types_list
    post   'upload',                       to: 'posts#upload', as: :upload
    post   'save-draft',                   to: 'posts#save_draft', as: :save_draft
    post   'delete-draft',                 to: 'posts#delete_draft', as: :delete_draft

    get    ':id',                          to: 'posts#show', as: :post
    get    ':id/history',                  to: 'post_history#post', as: :post_history
    get    ':id/edit',                     to: 'posts#edit', as: :edit_post
    patch  ':id/edit',                     to: 'posts#update', as: :update_post
    post   ':id/close',                    to: 'posts#close', as: :close_post
    post   ':id/reopen',                   to: 'posts#reopen', as: :reopen_post
    post   ':id/delete',                   to: 'posts#delete', as: :delete_post
    post   ':id/restore',                  to: 'posts#restore', as: :restore_post
    post   ':id/category',                 to: 'posts#change_category', as: :change_category
    post   ':id/toggle_comments',          to: 'posts#toggle_comments', as: :post_comments_allowance_toggle
    post   ':id/lock',                     to: 'posts#lock', as: :post_lock
    post   ':id/unlock',                   to: 'posts#unlock', as: :post_unlock
    post   ':id/feature',                  to: 'posts#feature', as: :post_feature
    post   ':id/promote',                  to: 'moderator#nominate_promotion', as: :promote_post
    delete ':id/promote',                  to: 'moderator#remove_promotion', as: :remove_post_promotion

    get    ':id/:answer',                  to: 'posts#show', as: :answer_post
  end

  get    'policy/:slug',                   to: 'posts#document', as: :policy
  get    'help/:slug',                     to: 'posts#document', as: :help

  get    'tags',                           to: 'tags#index', as: :tags

  scope 'users/two-factor' do
    root                                   to: 'two_factor#tf_status', as: :two_factor_status
    post 'enable',                         to: 'two_factor#enable_2fa', as: :two_factor_enable
    get  'enable/code',                    to: 'two_factor#enable_code', as: :two_factor_enable_code
    post 'enable/code',                    to: 'two_factor#confirm_enable_code', as: :two_factor_confirm_enable
    get  'disable/code',                   to: 'two_factor#disable_code', as: :two_factor_disable_code
    post 'disable/code',                   to: 'two_factor#confirm_disable_code', as: :two_factor_confirm_disable

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_moderator, except: [:users_global, :subs_global, :posts_global]
  before_action :verify_global_moderator, only: [:users_global, :subs_global, :posts_global]

  def users
    @users_all = User.joins(:community_users).where(community_users: { community_id: RequestContext.community_id })
                     .where('users.created_at >= ?', 1.year.ago)
    @users = @users_all.where("users.email NOT LIKE '%localhost'")
    @users_se = @users_all.where("users.email LIKE '%localhost'")
  end

  def subscriptions
    @subs = Subscription.where('created_at >= ?', 1.year.ago)
    @types = Subscription.all.group(:type).count
  end

  def posts
    @questions = Question.where('created_at >= ?', 1.year.ago).undeleted
    @answers = Answer.where('created_at >= ?', 1.year.ago).undeleted
    @comments = Comment.where('created_at >= ?', 1.year.ago).undeleted
    @this_month = Post.where('created_at >= ?', 1.month.ago).undeleted
    @categories = Category.where('IFNULL(categories.min_view_trust_level, 0) <= ?', current_user&.trust_level || 0)
                          .order(:sequence)
    @posts_categories = Post.where(category: @categories).group(:category_id).count
  end

  def reactions
    @reaction_types = ReactionType.active
    @reactions = Reaction.all
    @users = Reaction.select(:user_id).distinct
  end

  def users_global
    @users_all = User.where('users.created_at >= ?', 1.year.ago)
    @users = @users_all.where("users.email NOT LIKE '%localhost'")
    @users_se = @users_all.where("users.email LIKE '%localhost'")
    render :users
  end

  def subs_global
    @subs = Subscription.unscoped.where('created_at >= ?', 1.year.ago)
    @types = Subscription.unscoped.all.group(:type).count
    render :subscriptions
  end

  def posts_global
    @questions = Post.unscoped.where(post_type_id: Question.post_type_id).where('created_at >= ?', 1.year.ago).undeleted
    @answers = Post.unscoped.where(post_type_id: Answer.post_type_id).where('created_at >= ?', 1.year.ago).undeleted
    @comments = Comment.unscoped.where('created_at >= ?', 1.year.ago).undeleted
    @this_month = Post.unscoped.where('created_at >= ?', 1.month.ago).undeleted
    @categories = Category.unscoped
                          .where('IFNULL(categories.min_view_trust_level, 0) <= ?', current_user&.trust_level || 0)
                          .includes(:community).order(:community_id, :sequence)
    @posts_categories = Post.unscoped.where(category: @categories).group(:category_id).count
    @global = true
    render :posts
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_tabs.html.erb
<%= link_to moderator_path, class: 'has-font-size-small' do %>
  &laquo; Return to moderator tools
<% end %>

<% global = current_page?(global_users_report_path) ||
            current_page?(global_subs_report_path) ||
            current_page?(global_posts_report_path) %>

<% if global %>
  <div class="button-list is-gutterless has-margin-bottom-4">
    <%= link_to 'Users', global_users_report_path, class: "button is-muted is-outlined #{current_page?(global_users_report_path) ? 'is-active' : ''}" %>
    <%= link_to 'Posts', global_posts_report_path, class: "button is-muted is-outlined #{current_page?(global_posts_report_path) ? 'is-active' : ''}" %>
    <%= link_to 'Subscriptions', global_subs_report_path,
                class: "button is-muted is-outlined #{current_page?(global_subs_report_path) ? 'is-active' : ''}" %>
  </div>
<% else %>
  <div class="button-list is-gutterless has-margin-bottom-4">
    <%= link_to 'Users', users_report_path, class: "button is-muted is-outlined #{current_page?(users_report_path) ? 'is-active' : ''}" %>
    <%= link_to 'Posts', posts_report_path, class: "button is-muted is-outlined #{current_page?(posts_report_path) ? 'is-active' : ''}" %>
    <%= link_to 'Subscriptions', subscriptions_report_path,
                class: "button is-muted is-outlined #{current_page?(subscriptions_report_path) ? 'is-active' : ''}" %>
    <%= link_to 'Reactions', reactions_report_path,
                class: "button is-muted is-outlined #{current_page?(reactions_report_path) ? 'is-active' : ''}" %>
  </div>
<% end %>

app/views/reports/posts.html.erb
<%= render 'tabs' %>

<div class="flex-row">
  <%= stat_panel 'questions', @questions.count %>
  <%= stat_panel 'answers', @answers.count %>
  <%= stat_panel 'comments', @comments.count %>
  <%= stat_panel 'posts this month', @this_month.count %>
</div>

<h3>Categories</h3>
<div class="flex-row">
  <% @categories.each do |cat| %>
    <%= stat_panel cat.name, @posts_categories[cat.id] || 0, caption: @global ? cat.community.name : nil %>
  <% end %>
</div>

<h3>New posts</h3>
<%= line_chart [
  { name: 'Questions', data: @questions.group_by_week(:created_at).count },
  { name: 'Answers', data: @answers.group_by_week(:created_at).count },
  { name: 'Comments', data: @comments.group_by_week(:created_at).count },
] %>

app/views/reports/reactions.html.erb
<%= render 'tabs' %>

<div class="flex-row">
  <%= stat_panel 'reaction types', @reaction_types.count %>
  <%= stat_panel 'reactions', @reactions.count %>
  <%= stat_panel 'users', @users.count %>
</div>
<h3>Reaction usage</h3>
<%= line_chart Reaction.where('reactions.created_at >= ?', 1.year.ago).where(reaction_type: @reaction_types)
                       .group(:reaction_type_id).group_by_week(:created_at).count
                       .reduce({}) { |acc, val| acc[val[0][0]] ||= []; acc[val[0][0]] << ({val[0][1] => val[1]}); acc }
                       .map { |k, v| { name: @reaction_types.select { |x| x.id == k }[0].name,
                                       data: v.map(&:to_a)[0] } } %>

app/views/reports/subscriptions.html.erb
<%= render 'tabs' %>

<div class="flex-row">
  <%= stat_panel 'all', @types.map { |_, v| v }.sum %>
  <%= stat_panel 'interesting', @types['interesting'] %>
  <%= stat_panel 'tag', @types['tag'] %>
  <%= stat_panel 'user', @types['user'] %>
</div>

<h3>New subscriptions</h3>
<%= line_chart Subscription.where('created_at >= ?', 1.year.ago).group_by_week(:created_at).count %>

app/views/reports/users.html.erb
<%= render 'tabs' %>

<div class="flex-row">
  <%= stat_panel 'users', number_to_human(@users_all.count, format: '%n%u', units: { thousand: 'k', million: 'M' }) %>

  <%= stat_panel 'native signups',
                 number_to_human(@users.count, format: '%n%u', units: { thousand: 'k', million: 'M' }) %>

  <%= stat_panel 'from se',
                 number_to_human(@users_se.count, format: '%n%u', units: { thousand: 'k', million: 'M' }) %>

  <%= stat_panel 'this month',
                 number_to_human(@users.where('users.created_at >= ?', 1.month.ago).count, format: '%n%u', units: { thousand: 'k', million: 'M' }) %>
</div>

<h3>New signups</h3>
<%= line_chart @users.group_by_week(:created_at).count %>